#!/bin/bash

##########################################################################
# Copyright (C) [2013] [The FURTHeR Project]
#
# Licensed under the Apache License, Version 2.0 (the "License");
# you may not use this file except in compliance with the License.
# You may obtain a copy of the License at
#
#         http://www.apache.org/licenses/LICENSE-2.0
#
# Unless required by applicable law or agreed to in writing, software
# distributed under the License is distributed on an "AS IS" BASIS,
# WITHOUT WARRANTIES OR CONDITIONS OF ANY KIND, either express or implied.
# See the License for the specific language governing permissions and
# limitations under the License.
##########################################################################


###################################################################
# Oracle auto start-stop script. Must be run by the oracle user.
#
# Created by:   Rick, sometime in late 2008 or early 2009
# Last updated: Oren, April 20, 2009
###################################################################

# Set up environment
source $HOME/.bash_profile
export ORACLE_OWNER="oracle"
export CMD_FILE="/tmp/oracle-commands"
export SQLPLUS_CMD="sqlplus / as sysdba"
export HEADER_DECORATOR=

case "$1" in
    'start')
        # Start the Oracle databases
        # The following commands assumes that the oracle login
        # will not prompt the user for any values

	# Start the Oracle listener on port 1521
        echo "#######################################################################"
        echo "#                          Starting listener                          #"
        echo "#######################################################################"
	lsnrctl start

	# Start the database
	echo ""
        echo "#######################################################################"
        echo "#                          Starting database                          #"
        echo "#######################################################################"
        echo "startup;" > $CMD_FILE
        echo "exit;" >> $CMD_FILE
        cat $CMD_FILE | $SQLPLUS_CMD
	rm -f $CMD_FILE

	# Start the web front-end
	echo ""
        echo "#######################################################################"
        echo "#                          Starting OEM web front end                 #"
        echo "#######################################################################"
	emctl start dbconsole
        ;;
    'stop')
        # Stop the Oracle databases
        # The following commands assumes that the oracle login 
        # will not prompt the user for any values

	# Stop the web front-end
        echo "#######################################################################"
        echo "#                          Stopping OEM web front end                 #"
        echo "#######################################################################"
	emctl stop dbconsole

	# Stop the database
	echo ""
        echo "#######################################################################"
        echo "#                          Stopping database                          #"
        echo "#######################################################################"
        echo "shutdown immediate;" > $CMD_FILE
        echo "exit;" >> $CMD_FILE
        cat $CMD_FILE | $SQLPLUS_CMD
	rm -f $CMD_FILE

	# Stop the Oracle listener on port 1521
	echo ""
        echo "#######################################################################"
        echo "#                          Stopping listener                          #"
        echo "#######################################################################"
	lsnrctl stop
        ;;
    *)
	echo "usage: $0 <start|stop>"
	;;
esac
