#!/bin/bash

##########################################################################
# Copyright (C) [2013] [The FURTHeR Project]
#
# Licensed under the Apache License, Version 2.0 (the "License");
# you may not use this file except in compliance with the License.
# You may obtain a copy of the License at
#
#         http://www.apache.org/licenses/LICENSE-2.0
#
# Unless required by applicable law or agreed to in writing, software
# distributed under the License is distributed on an "AS IS" BASIS,
# WITHOUT WARRANTIES OR CONDITIONS OF ANY KIND, either express or implied.
# See the License for the specific language governing permissions and
# limitations under the License.
##########################################################################

##############################################################################
# Start the ESB on the production linux VM (dev-esb).
# 
# Author: Oren E. Livne
# Date: 29-JAN-2010
##############################################################################

progname=`basename $0`

if [[ ($# -ne 0) ]]; then
    echo "Usage: $0"
    echo ""
    echo "Start the ESB in server mode in no-hickup mode."
    exit 1
fi

nohup $ESB_HOME/bin/servicemix server >&$LOG_HOME/esb.log &
echo "Staring ESB"
